repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
        name: isort (python)
      - id: isort
        args: ["--profile", "black"]
        name: isort (cpython)
      - id: isort
        args: ["--profile", "black"]
        name: isort (pyi)
        types: [pyi]
  - repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext", "md"]
      - id: no-commit-to-branch
        args:
          [
            "--branch",
            "master",
            "--pattern",
            "^(?!hotfix|feature).+",
          ]
      - id: mixed-line-ending
        args: ["--fix", "no"]
